name: Run tests

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      - run: npm ci
      - name: Run unit tests
        run: npm run test:unit
      - name: Build
        run: npm run build
      - name: Run end to end tests
        run: npm run test:e2e